# Q7

## CrossOver for binary representation

In [7]:
import numpy as np

def uniform_crossover(parent1, parent2):
    if len(parent1) != len(parent2):
        raise ValueError("Both parents must have the same length")

    # Initialize the children
    child1, child2 = [], []

    for i in range(len(parent1)):
        # Generate a random number for each position
        if np.random.rand() > 0.5:
            child1.append(parent1[i])
            child2.append(parent2[i])
        else:
            child1.append(parent2[i])
            child2.append(parent1[i])

    return child1, child2



def binaryCrossover(parent1 , parent2 , kind , crossover_probability) :
    if np.random.rand() < crossover_probability:
        if kind == '1-point' :
            point = np.random.randint(1, len(parent1)-1)
            offspring1 = np.concatenate((parent1[:point], parent2[point:]))
            offspring2 = np.concatenate((parent2[:point], parent1[point:]))
            
            return offspring1, offspring2
        
        
        elif kind == 'uniform' :
            offspring1, offspring2 = uniform_crossover(parent1, parent2)[0] , uniform_crossover(parent1, parent2)[1]
            return offspring1, offspring2
            
    else:
        return parent1, parent2

    
parent1 = [1, 0, 1, 0, 1, 1]
parent2 = [0, 1, 0, 1, 0, 0]

print(binaryCrossover(parent1 , parent2 ,'1-point' , 0.7)[0],binaryCrossover(parent1 , parent2 ,'1-point' , 0.7)[1])

[1 1 0 1 0 0] [0 1 0 0 1 1]


## mutation for binary representation

In [30]:
def binaryMutate(offspring, mutation_probability):
    for i in range(len(offspring)):
        t = np.random.rand()
        print(t)
        if t < mutation_probability:
            offspring[i] = 1 - offspring[i]
    return offspring

parent1 = [1, 0, 1, 0, 1, 1]
parent2 = [0, 1, 0, 1, 0, 0]

binaryMutate(parent1, 0.1)

0.9810628520593141
0.11619678086133944
0.013090101603985382
0.07346877483868886
0.17504822813405108
0.4176180235501231


[1, 0, 0, 1, 1, 1]

## Int Crossover :

In [31]:
def n_point_crossover(parent1, parent2, n):
    if len(parent1) != len(parent2):
        raise ValueError("Both parents must have the same length")
    if n <= 0 or n >= len(parent1):
        raise ValueError("n must be between 1 and the length of the parents - 1")

    # Generate n unique crossover points
    points = np.sort(np.random.choice(range(1, len(parent1)), n, replace=False))

    # Initialize the children
    child1, child2 = [], []

    # Alternate starting parent
    current_parent = True  # True for parent1, False for parent2

    # Starting from the beginning, add segments from alternating parents
    start_idx = 0
    for point in points:
        if current_parent:
            child1.extend(parent1[start_idx:point])
            child2.extend(parent2[start_idx:point])
        else:
            child1.extend(parent2[start_idx:point])
            child2.extend(parent1[start_idx:point])
        start_idx = point
        current_parent = not current_parent

    # Add the last segment
    if current_parent:
        child1.extend(parent1[start_idx:])
        child2.extend(parent2[start_idx:])
    else:
        child1.extend(parent2[start_idx:])
        child2.extend(parent1[start_idx:])

    return child1, child2

parent1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
parent2 = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
n = 3  # For example, 3-point crossover

child1, child2 = n_point_crossover(parent1, parent2, n)

print("Child 1:", child1)
print("Child 2:", child2)

Child 1: [1, 2, 8, 7, 6, 5, 4, 8, 2, 1]
Child 2: [10, 9, 3, 4, 5, 6, 7, 3, 9, 10]


## Int Mutation :

In [77]:
def creep_mutation(parent, mutation_range):
    child = parent + np.random.uniform(-mutation_range, mutation_range, size=len(parent))
    child = np.round(child)
    return child

parent1 = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
mutation_range = 2

creep_mutation(parent1, mutation_range)

array([ 12.,  19.,  29.,  42.,  50.,  60.,  72.,  80.,  91., 101.])

In [44]:
def random_resetting_mutation(parent, gene_values):
    gene_index = np.random.randint(len(parent))
    old_value = parent[gene_index]
    possible_values = [v for v in gene_values[gene_index] if v != old_value]

    if not possible_values:
        new_value = old_value
    else:
        new_value = np.random.choice(possible_values)

    child = np.copy(parent)
    child[gene_index] = new_value

    return child



parent = np.array([1, 2, 3]) 



# Define possible gene values (workers) for each task

gene_values = [[1, 2, 3], [1, 2, 3], [1, 2, 3]]

# Apply random resetting mutation

mutated_child = random_resetting_mutation(parent, gene_values)

mutated_child

array([1, 3, 3])

## float Crossover

In [66]:
def simple_arithmetic_crossover(parent1, parent2, alpha=0.5):

    crossover_point = np.random.randint(1, len(parent1))  # Exclude the first gene to ensure crossover happens

    child1 = np.copy(parent1)
    child2 = np.copy(parent2)

    child1[crossover_point:] = alpha * parent1[crossover_point:] + (1 - alpha) * parent2[crossover_point:]
    child2[crossover_point:] = alpha * parent2[crossover_point:] + (1 - alpha) * parent1[crossover_point:]

    return child1, child2

parent1 = np.array([0.1, 0.2, 0.3, 0.4, 0.5 , 0.6 , 0.7 , 0.8 , 0.9])
parent2 = np.array([0.3 , 0.2 , 0.3 , 0.2 , 0.3 , 0.2 , 0.3 , 0.2 , 0.3])

def whole_arithmetic_crossover(parent1, parent2, alpha=0.5):

    child1 = alpha * parent1 + (1 - alpha) * parent2
    child2 = alpha * parent2 + (1 - alpha) * parent1

    return child1, child2


def blend_crossover(parent1, parent2, alpha=0.5):
    if len(parent1) != len(parent2):
        raise ValueError("Both parents must have the same length")

    child1, child2 = np.empty_like(parent1), np.empty_like(parent2)

    for i in range(len(parent1)):
        c_min = min(parent1[i], parent2[i])
        c_max = max(parent1[i], parent2[i])
        range_min = c_min - alpha * (c_max - c_min)
        range_max = c_max + alpha * (c_max - c_min)

        child1[i] = np.random.uniform(range_min, range_max)
        child2[i] = np.random.uniform(range_min, range_max)

    return child1, child2

def float_crossOver(a , b , kind , Alpha , probability ):
    if np.random.rand() < probability:
        if kind == 'simple_arithmetic':
            return simple_arithmetic_crossover(a, b, alpha=Alpha)
        elif kind == 'whole_arithmetic' :
            return whole_arithmetic_crossover(a, b, alpha=Alpha)
        elif kind == 'blend' :
            return blend_crossover(a, b, alpha=Alpha)
    else : 
        return a , b
    
float_crossOver(parent1 , parent2 , 'simple_arithmetic' , 0.5 , 0.9 )
print('simple_arithmetic :' )
print(float_crossOver(parent1 , parent2 , 'simple_arithmetic' , 0.5 , 0.9 )[0],float_crossOver(parent1 , parent2 , 'simple_arithmetic' , 0.5 , 0.9 )[1])
print('whole_arithmetic :' )
print(float_crossOver(parent1 , parent2 , 'whole_arithmetic' , 0.5 , 0.9 )[0],float_crossOver(parent1 , parent2 , 'whole_arithmetic' , 0.5 , 0.9 )[1])
print('blend :' )
print(float_crossOver(parent1 , parent2 , 'blend' , 0.5 , 0.9 )[0],float_crossOver(parent1 , parent2 , 'blend' , 0.5 , 0.9 )[1])

simple_arithmetic :
[0.1 0.2 0.3 0.3 0.4 0.4 0.5 0.5 0.6] [0.3 0.2 0.3 0.2 0.3 0.4 0.5 0.5 0.6]
whole_arithmetic :
[0.2 0.2 0.3 0.3 0.4 0.4 0.5 0.5 0.6] [0.2 0.2 0.3 0.3 0.4 0.4 0.5 0.5 0.6]
blend :
[0.18661647 0.2        0.3        0.46614849 0.26047256 0.75679697
 0.4586081  0.31019968 0.74167838] [ 0.35395041  0.2         0.3         0.19724598  0.58874525  0.53420182
  0.47477628 -0.02467616  0.97265105]


## float Mutation

In [80]:
def uncorrelated_mutation_one_sigma(parent, sigma, tau_prime):

    sigma_prime = sigma * np.exp(tau_prime * np.random.normal())

    sigma_prime = max(sigma_prime, 1e-20)

    mutated_parent = parent + sigma_prime * np.random.normal(size=len(parent))

    return mutated_parent, sigma_prime

initial_sigma = 0.1
tau_prime = 1 / np.sqrt(2 * len(parent))
mutated_parent, new_sigma = uncorrelated_mutation_one_sigma(parent1, initial_sigma, tau_prime)

print("Mutated Parent:", mutated_parent)
print("New Sigma:", new_sigma)

Mutated Parent: [10.04094601 20.17920203 30.12594615 39.93845691 49.8313346  60.00164041
 69.87743397 80.13014961 90.04081945 99.81265724]
New Sigma: 0.13096524339621643


In [85]:
def uncorrelated_mutation_n_sigmas(parent, sigmas, tau, tau_prime):
    n = len(parent)

    sigmas_prime = sigmas * np.exp(tau * np.random.normal() + tau_prime * np.random.normal(size=n))

    sigmas_prime = np.maximum(sigmas_prime, 1e-20)

    mutated_parent = parent + sigmas_prime * np.random.normal(size=n)

    return mutated_parent, sigmas_prime

sigmas = np.array([0.1, 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1])
tau = 1 / np.sqrt(2 * np.sqrt(len(parent1)))
tau_prime = 1 / np.sqrt(2 * len(parent1))

mutated_parent, new_sigmas = uncorrelated_mutation_n_sigmas(parent1, sigmas, tau, tau_prime)
print("Mutated Parent:", mutated_parent)
print("New Sigmas:", new_sigmas)

Mutated Parent: [  9.99088869  20.02436957  30.15566177  39.98923534  49.97696959
  60.0465848   70.00018999  79.93888002  89.94233833 100.07030047]
New Sigmas: [0.06293322 0.12427188 0.13484502 0.11367701 0.08162446 0.1412326
 0.08692515 0.0597612  0.08478881 0.12396078]
